#+TITLE: README
#+AUTHOR: DarkSun
#+CATEGORY: pocket-api.el
#+DATE: [2016-05-23 一 20:24]
#+OPTIONS: ^:{}

* what's pocket-api
Another pocket api which is rewriten from [[https://github.com/pterygota/el-pocket][el-pocket]]. 

* Why another pocket api
There is already a pocket api in elisp called [[https://github.com/pterygota/el-pocket][el-pocket]]. 
But it doesn't support emacs25 and the author seems disappeared over one year.
So I create this project.

* Usage
The usage is similar with [[https://github.com/pterygota/el-pocket][el-pocket]]. 

The first time using `pocket-api', you should execute =pocket-api-authorize= twice.

1. The first time execute =pocket-api-authorize= you will be directed to the oauth/request page, where you can click on authorize. After authorizing, you may see an error page, but it don't matter.

2. And then, the second time execute =pocket-api-authorize= you will get the access token, and it will be saved to =~/.el-pocket-auth.json=
   
After that, you don't need to do the authorizing job any more, just use =(el-pocket-load-auht)= to reload the access token.

Usng =M-x el-pocket-add= to add URLs
