* pocket-lib

This is a simple library for accessing the [[https://getpocket.com/developer/docs/v3/][getpocket.com API]].  It is in alpha status at the moment, only supporting =get= and =archive= functions.

* Usage

** Authorize

First you must authorize this library to access your Pocket account.

1.  Open your web browser to the Pocket web site, and log out of Pocket.  (It seems to only work if you are logged out.)
2.  Run =pocket-lib-get= (this is not an interactive command, so you should call it in the minibuffer like ~(pocket-lib-get)~; typically this will be handled for you by packages that use this library).  A URL will be copied to the clipboard and kill-ring.
3.  Visit that URL in your browser, and authorize it.
4.  Run =pocket-lib-get= again.  If it worked, you should see an ugly list of data containing the first 10 items on your list.

Now you can use the library.

** Functions

+  =pocket-lib-get=  Get items on the reading list.  Call with keyword arguments, as listed in the API docs, to get different kinds of items (e.g. archived, favorited, tagged).
+  =pocket-lib-archive=  Archive one or more items.  Call with items retrieved with =pocket-lib-get=.

* Credits

This package is based on [[https://github.com/lujun9972/pocket-api.el][pocket-api.el]] by [[https://github.com/lujun9972/pocket-api.el][DarkSun/lujun9972]], which is based on [[https://github.com/pterygota/el-pocket][el-pocket]] by [[https://github.com/pterygota/el-pocket][Tod Davies]].  It has essentially been completely written; no code remains except =pocket-lib-default-extra-headers=, a few lines in the call to =request=, and the consumer key is currently the same.

* License

GPLv3
